server:
  port: 8080

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: users
          uri: http://localhost:8090
          predicates:             
            - Path=/api/v1/users/**
        - id: employees
          uri: http://localhost:8100
          predicates:             
            - Path=/api/v1/employee/**
  cliente:
    register-with-eureka: false
 
        